#docker-compose up
version: "3"

services:
  app:
    build: .
    enviroment:
      Mongo_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000-3010:3000"
    volumes:
      - .:/usr/src

  db:
    image: mariadb:10.3

#docker-compose down